############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: # 把对应的那一行注释掉就使用本地的文件
    css:
      # style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.4.10/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.4.10/js/app.js
      search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.4.9/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1/js/volantis.min.js



############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true
busuanzi: true
# fastclick: true



############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true      # 是否启用
  color: '#1BCDFC'  # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 2615636388    # 歌曲/专辑/歌单 ID
  volume: 0.7       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
loading_img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png

# 日期格式 http://momentjs.com/docs/
date_format: 'll' # 文章发布日期的格式
updated_date_format: 'llll' # 文章更新日期的格式


############################### 自定义 ###############################
# 主页封面
cover:
  scheme: search    # 后期将会提供多种封面方案
  height: half      # full: 封面占据整个第一屏幕， half: 封面只占半个屏幕高度
  title: "·appx·"
  # logo: assets/logo.png
  # search_placeholder: '搜索'
  # 主页封面菜单
  features:
    - name: Recent
      icon: fas fa-clock
      url: /
    - name: Windows
      icon: fab fa-windows
      url: categories/windows/
    - name: Mac
      icon: fab fa-apple
      url: categories/mac/
    - name: Android
      icon: fab fa-android
      url: categories/android/
    - name: iOS
      icon: fab fa-apple
      url: categories/ios/


# 桌面端导航栏菜单
menu_desktop:
  - name: Windows
    icon: fab fa-windows
    url: categories/windows/
  - name: Mac
    icon: fab fa-apple
    url: categories/mac/
  - name: Android
    icon: fab fa-android
    url: categories/android/
  - name: iOS
    icon: fab fa-apple
    url: categories/ios/

# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: Windows
    icon: fab fa-windows
    url: categories/windows/
  - name: Mac
    icon: fab fa-apple
    url: categories/mac/
  - name: Android
    icon: fab fa-android
    url: categories/android/
  - name: iOS
    icon: fab fa-apple
    url: categories/ios/


# 侧边栏小部件，默认按下面给定的顺序全部显示，文章中还可以自定义显示一部分以及顺序
sidebar:
  - widget: author
    avatar: https://img.vim-cn.com/ae/2e0ffa7c770dbebba64f2f1770c29788a09e24.png
  - widget: grid
    icon: fas fa-map-signs
    title: Navigation
    rows:
      - name: Recent
        icon: fas fa-clock
        url: /
      - name: Timeline
        icon: fas fa-archive
        url: archives/
      - name: Forum
        icon: fas fa-comments
        url: forum/
  - widget: tagcloud
    start_color: '#999'
    end_color: '#EEE'
  - widget: related_posts


# 社交信息
social:
  - icon: fas fa-rss
    url: atom.xml
  - icon: fas fa-envelope
    url: mailto:me@xaoxuu.com
  - icon: fab fa-github
    url: https://github.com/appx-online


# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  # - id: qrcode
  #   name: 微信
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  # - id: qrcode
  #   name: QRcode
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png



footer: '本站所有下载链接均标注文件来源，如果部分第三方下载源的软件侵犯了开发商或者合法代理商的权利，可联系站长删除该链接。'



############################### 评论 ###############################
# disqus_shortname: xaoxuu
# livere_uid:
# valine
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 20 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn
  highlight: false





############################### 杂项，请勿删除 ###############################
# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
